Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "project6"
        vb.memory = 2048
        vb.cpus = 2
        vb.gui = true
    end

    config.vm.provision "shell", path: "init.sh"
    config.vm.provision "file", source: "./empty_file", destination: "$HOME/empty_file"
end
